name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        env:
             GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Clear SSH known hosts
            run: |
              mkdir -p ~/.ssh  
              rm -f ~/.ssh/known_hosts
              ssh-keyscan github.com >> ~/.ssh/known_hosts
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
